"""add column called content_type to files table

Revision ID: 9ecbf0b7098e
Revises: e045ef8d597d
Create Date: 2025-04-05 09:16:37.789342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecbf0b7098e'
down_revision: Union[str, None] = 'e045ef8d597d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Files', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Files', 'content_type')
    # ### end Alembic commands ###
